#ifndef PHYTH_CURRENT_SEGMENT_HPP
#define PHYTH_CURRENT_SEGMENT_HPP

#include "MagneticSource.hpp"
#include "Phyth/Physical/PhysicalConsts.hpp"
#include <cmath>
#include <stdexcept>

namespace Phyth::Electromagnetics {
    /**
     * @brief Magnetic field from a straight current-carrying wire segment
     *
     * CurrentSegment computes the magnetic field generated by a finite
     * straight wire segment carrying a steady current, using the Biot-Savart
     * law in closed form.
     *
     * The magnetic field direction follows the right-hand rule around the
     * current direction (from start to end).
     *
     * Example:
     *   auto start = Vector3<Quantity<Meter>>(-1.0_m, 0_m, 0_m);
     *   auto end = Vector3<Quantity<Meter>>(1.0_m, 0_m, 0_m);
     *   auto current = 5.0_A;
     *
     *   CurrentSegment wire(start, end, current);
     *   auto point = Vector3<Quantity<Meter>>(0_m, 0.1_m, 0_m);
     *   auto B = wire.GetMagneticFieldAt(point);
     *
     * Note: The field is singular on the wire axis. Points on the wire
     *       will throw an exception.
     */
    class CurrentSegment : public MagneticSource {
    public:
        /**
         * @brief Construct a current segment from start to end
         *
         * @param start Starting point of the segment (meters)
         * @param end Ending point of the segment (meters)
         * @param current Current flowing from start to end (Amperes)
         *
         * @throws std::invalid_argument If segment length is zero
         */
        CurrentSegment(const Vector3<Quantity<Meter> > &start,
                       const Vector3<Quantity<Meter> > &end,
                       const Quantity<Ampere> &current)
            : start_(start), end_(end), current_(current) {
            const auto delta = end_ - start_;
            length_ = delta.Length();

            if (length_ < Quantity<Meter>(Config::epsilon)) {
                throw std::invalid_argument("CurrentSegment: segment length must be non-zero");
            }

            direction_ = delta / length_;
        }

        /**
         * @brief Compute the magnetic field at a point
         *
         * @param point Position in 3D space (meters)
         * @return Magnetic flux density B (Tesla) as a Vector3
         *
         * @throws std::runtime_error If the point lies on the wire axis
         *
         * The field is computed using the Biot-Savart law closed-form
         * solution for a finite straight wire.
         */
        [[nodiscard]] Vector3<Quantity<Tesla> >
        GetMagneticFieldAt(const Vector3<Quantity<Meter> > &point) const override {
            if (IsPointOnWire(point)) {
                throw std::runtime_error("CurrentSegment: point lies on the wire axis");
            }

            return AnalyticSolution(point);
        }

        /** @return The current flowing through the segment (Amperes) */
        [[nodiscard]] Quantity<Ampere> GetCurrent() const {
            return current_;
        }

        /** @return The length of the segment (meters) */
        [[nodiscard]] Quantity<Meter> GetLength() const {
            return length_;
        }

        /** @return The starting point of the segment */
        [[nodiscard]] const Vector3<Quantity<Meter> > &GetStart() const {
            return start_;
        }

        /** @return The ending point of the segment */
        [[nodiscard]] const Vector3<Quantity<Meter> > &GetEnd() const {
            return end_;
        }

    private:
        Vector3<Quantity<Meter> > start_;
        Vector3<Quantity<Meter> > end_;
        Vector3<Scalar> direction_;
        Quantity<Meter> length_;
        Quantity<Ampere> current_;

        /**
         * @brief Closed-form Biot-Savart solution for a finite straight wire
         *
         * The magnetic field at a point P is:
         *   B = (mu_0 * I / (4 * pi * rho)) *
         *       (z2/sqrt(rho^2 + z2^2) - z1/sqrt(rho^2 + z1^2)) * phi_hat
         *
         * where:
         *   - rho is the perpendicular distance from P to the wire axis
         *   - z1, z2 are the distances from the projection point to the ends
         *   - phi_hat is the azimuthal unit vector around the wire
         *
         * @param point Position to evaluate the field
         * @return Magnetic field at that point
         *
         * If rho is near zero (point on the wire axis), returns zero
         * instead of throwing. The singularity is handled by the caller.
         */
        [[nodiscard]] Vector3<Quantity<Tesla> >
        AnalyticSolution(const Vector3<Quantity<Meter> > &point) const {
            const auto r_vec = point - start_;
            const auto proj = r_vec.Dot(direction_);

            const auto perp_vec = r_vec - proj * direction_;
            const auto rho = perp_vec.Length();

            // If point is on the wire axis, field is undefined.
            // Return zero instead of blowing up.
            if (rho < Config::epsilon * length_) {
                return Vector3{0_T, 0_T, 0_T};
            }

            const auto z1 = -proj;
            const auto z2 = length_ - proj;

            const auto rho2 = rho * rho;
            const auto term1 = z2 / Utils::sqrt(rho2 + z2 * z2);
            const auto term2 = z1 / Utils::sqrt(rho2 + z1 * z1);
            const auto angular_factor = term1 - term2;

            const auto B_mag = Consts::mu_0 * current_ / (4 * Consts::pi * rho) * angular_factor;

            const auto perp_hat = perp_vec.Normalized();
            const auto phi_hat = direction_.Cross(perp_hat);

            return B_mag * phi_hat;
        }

        /**
         * @brief Check if a point lies on the wire segment
         *
         * A point is considered "on the wire" if it is within tolerance
         * of the wire axis and its projection falls within the segment bounds.
         *
         * @param point Position to check
         * @return true if the point is on the wire segment
         */
        [[nodiscard]] bool
        IsPointOnWire(const Vector3<Quantity<Meter> > &point) const {
            const auto r_vec = point - start_;
            const auto proj = r_vec.Dot(direction_);

            const auto tol = Quantity(
                Utils::max(Config::epsilon * length_, Quantity<Meter>(Config::epsilon))
            );

            if (proj < -tol || proj > length_ + tol) {
                return false;
            }

            const auto perp_vec = r_vec - proj * direction_;
            const auto rho = perp_vec.Length();

            return rho < tol;
        }

        /**
         * @brief Compute the minimum distance from a point to the wire segment
         *
         * @param point Position to compute distance from
         * @return Minimum distance to the segment (meters)
         *
         * This is used by MagneticSource interface for regularization.
         */
        [[nodiscard]] Quantity<Meter>
        GetMinimumDistanceTo(const Vector3<Quantity<Meter> > &point) const {
            const auto v = point - start_;
            const auto proj = v.Dot(direction_);

            if (proj <= Quantity<Meter>(0)) {
                return v.Length();
            }

            if (proj >= length_) {
                return (point - end_).Length();
            }

            const auto closest = start_ + proj * direction_;
            return (point - closest).Length();
        }
    };
}

#endif // PHYTH_CURRENT_SEGMENT_HPP
